import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// 合并CSS文件的函数
function mergeCSS() {
	try {
		// 读取插件样式
		const pluginStyles = readFileSync('plugin-styles.css', 'utf8');
		// 读取渲染器样式
		const renderStyles = readFileSync('lib/render.css', 'utf8');
		
		// 合并CSS内容
		const mergedCSS = `/* Plugin Styles */\n${pluginStyles}\n\n/* Renderer Styles */\n${renderStyles}`;
		
		// 写入到styles.css
		writeFileSync('styles.css', mergedCSS);
		console.log('✅ CSS files merged successfully');
	} catch (error) {
		console.error('❌ Error merging CSS files:', error);
		process.exit(1);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	loader: {
		'.js': 'text',  // 将.js文件作为文本导入
	},
	plugins: [
		{
			name: 'merge-css',
			setup(build) {
				build.onEnd(() => {
					mergeCSS();
				});
			}
		}
	]
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
} 